[package]
name = "sp-runtime-interface-test-wasm-deprecated"
version = "2.0.0"
authors = ["Abel Technologies abelbeertech@outlook.com"]
edition = "2018"
build = "build.rs"
license = "Apache-2.0"
homepage = "http://www.abel.beer"
repository = "https://github.com/abelbeertech/abel-bkchain"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-runtime-interface = { version = "2.0.0", default-features = false, path = "../" }
sp-std = { version = "2.0.0", default-features = false, path = "../../std" }
sp-io = { version = "2.0.0", default-features = false, path = "../../io" }
sp-core = { version = "2.0.0", default-features = false, path = "../../core" }

[build-dependencies]
wasm-builder-runner = { version = "2.0.0", package = "substrate-wasm-builder-runner", path = "../../../utils/wasm-builder-runner" }

[features]
default = [ "std" ]
std = [ "sp-runtime-interface/std", "sp-std/std", "sp-core/std", "sp-io/std" ]
