[package]
name = "substrate-frame-cli"
version = "2.0.0"
authors = ["Abel Technologies abelbeertech@outlook.com"]
edition = "2018"
license = "Apache-2.0"
homepage = "http://www.abel.beer"
repository = "https://github.com/abelbeertech/abel-bkchain"
description = "cli interface for FRAME"
documentation = "https://docs.rs/substrate-frame-cli"
readme = "README.md"

[dependencies]
sp-core = { version = "2.0.0", path = "../../../primitives/core" }
sc-cli = { version = "0.8.0", path = "../../../client/cli" }
sp-runtime = { version = "2.0.0", path = "../../../primitives/runtime" }
structopt = "0.3.8"
frame-system = { version = "2.0.0", path = "../../../frame/system" }

[dev-dependencies]

[features]
default = []
